
vich_uploader:
    db_driver: orm
    mappings:
        upload_files:
            uri_prefix:         /app/img
            upload_destination: "%kernel.root_dir%/../web/app/img"

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true