<?php

namespace AppBundle\Repository;

/**
 * BonoboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonoboRepository extends \Doctrine\ORM\EntityRepository
{ public function findBonoboListByPage($user,$page){
	
	    $offset=$page*4;
		return $this->createQueryBuilder('a')
		->Where('a.id !=:current_id')
		->setParameter('current_id', $user )
 		->setMaxResults(4)
        ->setFirstResult($offset)
		->getQuery()
		->execute();
		;
}
 
public function findBonoboList($user){

		return $this->createQueryBuilder('a')
		->Where('a.id !=:current_id')
		->setParameter('current_id', $user )
 		->setMaxResults(4)
		->getQuery()
		->getResult();
		;

}
public function count($user){

	return $this->createQueryBuilder('a')
	 ->select('COUNT(a)')->Where('a.id !=:current_id')
		->setParameter('current_id', $user )
	 ->getQuery()
	 ->getSingleScalarResult();
}

}
